query ListAllTasks @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  tasks {
    id
    title
    description
    completed
    createdAt
    userUid
  }
}

mutation CreateTask($title: String!, $description: String!) @auth(level: USER) {
  task_insert(data: {
    title: $title,
    description: $description,
    completed: false,
    userUid_expr: "auth.uid",
    createdAt_expr: "request.time"
  })
}

mutation UpdateTaskStatus($id: UUID!, $completed: Boolean!) @auth(level: USER) {
  task_update(key: {id: $id}, data: {
    completed: $completed
  })
}

query GetMyTasks @auth(level: USER) {
  tasks(where: {userUid: {eq_expr: "auth.uid"}}) {
    id
    title
    description
    completed
    createdAt
  }
}